version: 2

builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - GOFLAGS=-mod=readonly
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    id: "steampipe"
    binary: "{{ .ProjectName }}.plugin"
    flags:
      - -tags=netgo

archives:
  - formats: [gz]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

checksum:
  name_template: "{{ .ProjectName }}_SHA256SUMS"
  algorithm: sha256

changelog:
  disable: true
