package anthropic

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"time"

	"github.com/turbot/steampipe-plugin-sdk/v6/grpc/proto"
	"github.com/turbot/steampipe-plugin-sdk/v6/plugin"
)

type anthropicComplianceChatMessage struct {
	Id             string          `json:"id"`
	Role           string          `json:"role"`
	CreatedAt      *time.Time      `json:"created_at"`
	Content        json.RawMessage `json:"content"`
	Files          json.RawMessage `json:"files"`
	GeneratedFiles json.RawMessage `json:"generated_files"`
	Artifacts      json.RawMessage `json:"artifacts"`
	ChatId         string          `json:"-"`
}

type anthropicComplianceChatMessagesPage struct {
	Id           string                           `json:"id"`
	ChatMessages []anthropicComplianceChatMessage `json:"chat_messages"`
	HasMore      bool                             `json:"has_more"`
	LastID       *string                          `json:"last_id"`
}

//// TABLE DEFINITION

func tableAnthropicComplianceChatMessage(_ context.Context) *plugin.Table {
	return &plugin.Table{
		Name:        "anthropic_compliance_chat_message",
		Description: "Messages within a claude.ai chat, retrieved via the Compliance API. Specify chat_id in the WHERE clause. Requires a Compliance Access Key with the read:compliance_user_data scope.",
		List: &plugin.ListConfig{
			KeyColumns: plugin.SingleColumn("chat_id"),
			Hydrate:    listComplianceChatMessages,
		},
		Columns: []*plugin.Column{
			{Name: "chat_id", Type: proto.ColumnType_STRING, Description: "Id of the chat the message belongs to."},
			{Name: "id", Type: proto.ColumnType_STRING, Description: "Unique message identifier (claude_chat_msg_...)."},
			{Name: "role", Type: proto.ColumnType_STRING, Description: "Role of the message author: user or assistant."},
			{Name: "created_at", Type: proto.ColumnType_TIMESTAMP, Description: "For user messages, when the message was sent; for assistant messages, when generation finished."},
			{Name: "content", Type: proto.ColumnType_JSON, Description: "Content blocks of the message."},
			{Name: "files", Type: proto.ColumnType_JSON, Description: "Binary uploads attached to the message (claude_file_...)."},
			{Name: "generated_files", Type: proto.ColumnType_JSON, Description: "Files generated by the assistant through tool use (claude_gen_file_...)."},
			{Name: "artifacts", Type: proto.ColumnType_JSON, Description: "Artifacts produced or updated by the assistant (claude_artifact_...)."},
		},
	}
}

//// LIST FUNCTION

func listComplianceChatMessages(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (interface{}, error) {
	chatID := d.EqualsQualString("chat_id")
	if chatID == "" {
		return nil, nil
	}

	client, err := getComplianceClient(ctx, d)
	if err != nil {
		plugin.Logger(ctx).Error("anthropic_compliance_chat_message.list", "connection_error", err)
		return nil, err
	}

	path := fmt.Sprintf("/v1/compliance/apps/chats/%s/messages", chatID)
	params := url.Values{}

	for {
		var page anthropicComplianceChatMessagesPage
		if err := client.getJSON(ctx, path, params, &page); err != nil {
			plugin.Logger(ctx).Error("anthropic_compliance_chat_message.list", "api_error", err)
			return nil, err
		}
		for _, msg := range page.ChatMessages {
			msg.ChatId = chatID
			d.StreamListItem(ctx, msg)
			if d.RowsRemaining(ctx) == 0 {
				return nil, nil
			}
		}
		if !page.HasMore || page.LastID == nil {
			return nil, nil
		}
		params.Set("after_id", *page.LastID)
	}
}
